apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ngrok.fullname" . }}
  labels:
    app: {{ template "ngrok.name" . }}
    chart: {{ template "ngrok.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ngrok.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ngrok.name" . }}
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - ./ngrok
            - http
            {{- if .Values.subdomain }}
            - --subdomain={{ .Values.subdomain }}
            {{- end }}
            - {{ .Values.expose.service }}
          volumeMounts:
          - name: config
            mountPath: /home/ngrok/.ngrok2
          ports:
            - name: http
              containerPort: 4040
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/tunnels
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "ngrok.fullname" . }}
